stages:
  - test
  - deploy

before_script:
  - apt-get update -qy
  - apt-get install -y python3
  - apt-get install -y python3-pip
  - pip3 install -r requirements.txt
  - pip3 install awsebcli

testing:
  stage: test
  script:
  - python3 manage.py test
  only:
  - develop

deployment:
  stage: deploy
  script:

  only:
  - master
